name: "Pull Request Labeler"

on:
  pull_request:
  workflow_dispatch:

jobs:
  labeler:
    name: Label PRs
    runs-on: ubuntu-latest
    steps:
      - name: Labeler
        uses: actions/labeler@v4
        with:
          configuration-path: .github/labeler.yaml
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
